# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_provider_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmethod',
            name='provider_id',
            field=models.CharField(choices=[('espoo_adfs', 'Espoo ADFS'), ('facebook', 'Facebook'), ('github', 'GitHub'), ('google', 'Google'), ('helsinki_adfs', 'Helsinki ADFS'), ('yletunnus', 'YleTunnus')], max_length=50, unique=True),
        ),
    ]
